development:
  umms_rws: http://dev-umms-rws.optilink.com:8082/
  secret_key: "@PT1L!NK"

test:
  umms_rws: http://dev-umms-rws.optilink.com:8082/
  secret_key: "@PT1L!NK"

production:
  umms_rws: http://prd-umms-rws.optilink.com:8080/
  secret_key: "@PT1L!NK"
